export const TEXT_FIELD = 'TEXT_FIELD';
export const RADIO_LIST = 'RADIO_LIST';
export const RADIO_SUB_ITEM = 'RADIO_SUB_ITEM';
export const DROPDOWN_LIST = 'DROPDOWN_LIST';
export const DROPDOWN_SUB_ITEM = 'DROPDOWN_SUB_ITEM';
export const SUBMIT_BUTTON = 'SUBMIT_BUTTON';
